POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY

###

GET http://localhost:3000/states/8/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY
###

POST http://localhost:3000/districts/
Content-Type: application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/327/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY
###

DELETE http://localhost:3000/districts/327/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY

###

PUT http://localhost:3000/districts/350/
Content-Type: application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/6/stats/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzIwMTQ3NjM1fQ.285Tvk6duBZYNU1z_0AiX_PjtDsr0fvwGpgr-6NhVNY

###